---
name: "pre-release"

on:
  push:
    branches:
      - "develop"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5

      - name: Build Linux x64
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -v -o focusrite-autoclock-$GOOS-$GOARCH ./src/.
      # - name: Build Linux arm64
      #   env:
      #     GOOS: linux
      #     GOARCH: arm64
      #   run: go build -v -o focusrite-autoclock-$GOOS-$GOARCH ./src/.
      # - name: Build Linux arm
      #   env:
      #     GOOS: linux
      #     GOARCH: arm
      #   run: go build -v -o focusrite-autoclock-$GOOS-$GOARCH ./src/.
      - name: Build Windows x64
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -v -o focusrite-autoclock-$GOOS-$GOARCH.exe ./src/.
      # - name: Build MacOS
      #   env:
      #     GOOS: darwin
      #     GOARCH: amd64
      #   run: go build -v -o focusrite-autoclock-$GOOS-$GOARCH ./src/.
      - name: Autorelease
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "develop"
          prerelease: true
          title: "Development Build"
          files: |
            focusrite-autoclock*
