---
name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build Linux x64
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -v -o focusrite-autoclock-$GOOS-$GOARCH ./src/.
      - name: Build Linux arm64
        env:
          GOOS: linux
          GOARCH: arm64
        run: go build -v -o focusrite-autoclock-$GOOS-$GOARCH ./src/.
      - name: Build Linux arm
        env:
          GOOS: linux
          GOARCH: arm
        run: go build -v -o focusrite-autoclock-$GOOS-$GOARCH ./src/.
      - name: Build Windows x64
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -v -o focusrite-autoclock-$GOOS-$GOARCH.exe ./src/.
      - name: Build MacOS
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -v -o focusrite-autoclock-$GOOS-$GOARCH ./src/.
      - name: Autorelease
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          # automatic_release_tag: "latest"
          draft: true
          prerelease: false
          # title: "Version release"
          files: |
            focusrite-autoclock*
